"""accounts schema

Revision ID: 0001_accounts
Revises: 
Create Date: 2026-07-12 19:40:27.699657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_accounts'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='accounts'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index('users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True, schema='accounts')
    op.create_table('designs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(owner_user_id IS NULL) <> (owner_org_id IS NULL)', name='designs_one_owner'),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_org_id'], ['accounts.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index('designs_owner_org', 'designs', ['owner_org_id'], unique=False, schema='accounts')
    op.create_index('designs_owner_user', 'designs', ['owner_user_id'], unique=False, schema='accounts')
    op.create_table('email_tokens',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose IN ('verify','reset')", name='email_tokens_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash'),
    schema='accounts'
    )
    op.create_index(op.f('ix_accounts_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False, schema='accounts')
    op.create_table('inventory_parts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_org_id', sa.UUID(), nullable=True),
    sa.Column('part_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('catalog_ref', sa.Text(), nullable=True),
    sa.Column('mas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mas_version', sa.Text(), nullable=True),
    sa.Column('lifecycle', sa.Text(), server_default=sa.text("'approved'"), nullable=False),
    sa.Column('stock_qty', sa.Numeric(), nullable=True),
    sa.Column('order_code', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("lifecycle IN ('draft','approved','deprecated','obsolete')", name='inventory_lifecycle'),
    sa.CheckConstraint("part_type IN ('coreShape','coreMaterial','core','bobbin','wire')", name='inventory_part_type'),
    sa.CheckConstraint("source IN ('catalog','private')", name='inventory_source'),
    sa.CheckConstraint('(owner_user_id IS NULL) <> (owner_org_id IS NULL)', name='inventory_one_owner'),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_org_id'], ['accounts.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index('inv_org_name', 'inventory_parts', ['owner_org_id', 'part_type', 'name'], unique=True, schema='accounts', postgresql_where=sa.text('owner_org_id IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('inv_user_name', 'inventory_parts', ['owner_user_id', 'part_type', 'name'], unique=True, schema='accounts', postgresql_where=sa.text('owner_user_id IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('invited_email', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('owner','admin','librarian','member','viewer')", name='memberships_role'),
    sa.ForeignKeyConstraint(['invited_by'], ['accounts.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['accounts.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index('memberships_org_user', 'memberships', ['org_id', 'user_id'], unique=True, schema='accounts')
    op.create_table('sessions',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash'),
    schema='accounts'
    )
    op.create_index(op.f('ix_accounts_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='accounts')
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='accounts'
    )
    op.create_table('design_revisions',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('mas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mas_hash', sa.Text(), nullable=False),
    sa.Column('mas_version', sa.Text(), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=True),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('saved_by', sa.UUID(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['accounts.designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_by'], ['accounts.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('design_id', 'revision'),
    schema='accounts'
    )
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=True),
    sa.Column('pinned_revision', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_org_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visit_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("(kind = 'design' AND design_id IS NOT NULL) OR (kind = 'inventory' AND ((owner_user_id IS NULL) <> (owner_org_id IS NULL)))", name='share_links_target'),
    sa.CheckConstraint("kind IN ('design','inventory')", name='share_links_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['design_id'], ['accounts.designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_org_id'], ['accounts.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='accounts'
    )
    op.create_table('inventory_mounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('share_link_id', sa.UUID(), nullable=False),
    sa.Column('mounter_user_id', sa.UUID(), nullable=True),
    sa.Column('mounter_org_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(mounter_user_id IS NULL) <> (mounter_org_id IS NULL)', name='mounts_one_owner'),
    sa.ForeignKeyConstraint(['mounter_org_id'], ['accounts.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mounter_user_id'], ['accounts.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_link_id'], ['accounts.share_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_mounts', schema='accounts')
    op.drop_table('share_links', schema='accounts')
    op.drop_table('design_revisions', schema='accounts')
    op.drop_table('user_settings', schema='accounts')
    op.drop_index(op.f('ix_accounts_sessions_user_id'), table_name='sessions', schema='accounts')
    op.drop_table('sessions', schema='accounts')
    op.drop_index('memberships_org_user', table_name='memberships', schema='accounts')
    op.drop_table('memberships', schema='accounts')
    op.drop_index('inv_user_name', table_name='inventory_parts', schema='accounts', postgresql_where=sa.text('owner_user_id IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('inv_org_name', table_name='inventory_parts', schema='accounts', postgresql_where=sa.text('owner_org_id IS NOT NULL AND deleted_at IS NULL'))
    op.drop_table('inventory_parts', schema='accounts')
    op.drop_index(op.f('ix_accounts_email_tokens_user_id'), table_name='email_tokens', schema='accounts')
    op.drop_table('email_tokens', schema='accounts')
    op.drop_index('designs_owner_user', table_name='designs', schema='accounts')
    op.drop_index('designs_owner_org', table_name='designs', schema='accounts')
    op.drop_table('designs', schema='accounts')
    op.drop_index('users_email_lower', table_name='users', schema='accounts')
    op.drop_table('users', schema='accounts')
    op.drop_table('organizations', schema='accounts')
    op.drop_table('audit_log', schema='accounts')
    # ### end Alembic commands ###
